#!/bin/bash

#export JAVA_HOME=/usr/java/jdk1.7.0_71
mvn clean
mvn package -Dmaven.test.skip=true
if [ $? -ne 0 ]; then
    exit 1
fi

cp target/mall-mvc-1.0-SNAPSHOT.war target/mall.war
cp -r target/mall-mvc-1.0-SNAPSHOT target/mall
mv target/mall/WEB-INF/lib/qinyuan*.jar target/mall/WEB-INF/
rm -rf target/mall/WEB-INF/lib/* target/mall/WEB-INF/classes/{hibernate*,spring*,log*}
mv target/mall/WEB-INF/qinyuan*.jar target/mall/WEB-INF/lib/
cd target/mall
tar -zcf mall.tar.gz *
mv mall.tar.gz ../
#cd ../
#rm -rf  ./mall
